// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/lin-snow/ech0/internal/handler/user"
	"github.com/lin-snow/ech0/internal/repository/user"
	"github.com/lin-snow/ech0/internal/service/user"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// BuildHandlers 使用wire生成的代码来构建Handlers实例
func BuildHandlers(db *gorm.DB) (*Handlers, error) {
	userRepositoryInterface := repository.NewUserRepository(db)
	userServiceInterface := service.NewUserService(userRepositoryInterface)
	userHandler := handler.NewUserHandler(userServiceInterface)
	handlers := NewHandlers(userHandler)
	return handlers, nil
}

// wire.go:

// UserSet 包含了构建 UserHandler 所需的所有 Provider
var UserSet = wire.NewSet(repository.NewUserRepository, service.NewUserService, handler.NewUserHandler)
