
set shell := ["bash", "-cu"]

BUILD_TIME      := `date -u +%Y-%m-%dT%H:%M:%SZ`
GIT_COMMIT      := `git rev-parse --short HEAD 2>/dev/null || echo unknown`

DOCKER_REGISTRY := env_var_or_default("DOCKER_REGISTRY", "sn0wl1n")
IMAGE_NAME      := env_var_or_default("IMAGE_NAME", "ech0")
IMAGE_TAG       := env_var_or_default("IMAGE_TAG", "latest")
OS              := env_var_or_default("OS", `go env GOHOSTOS`)
ARCH            := env_var_or_default("ARCH", `go env GOHOSTARCH`)

default:
    @just --list

[working-directory: '..']
build:
    @echo "Building image for platform: {{OS}}/{{ARCH}}"
    docker build --platform {{OS}}/{{ARCH}} \
        --build-arg TARGETOS={{OS}} \
        --build-arg TARGETARCH={{ARCH}} \
        --build-arg GIT_COMMIT={{GIT_COMMIT}} \
        --build-arg BUILD_TIME={{BUILD_TIME}} \
        -t {{DOCKER_REGISTRY}}/{{IMAGE_NAME}}:{{IMAGE_TAG}} -f docker/build.Dockerfile .

push:
    docker push {{DOCKER_REGISTRY}}/{{IMAGE_NAME}}:{{IMAGE_TAG}}
